In [4]:
import pandas as pd
import csv


## RESTORE POINT: restore  dataframe and list from CSV and/or pickle

In [8]:
# NOT USED.  Pickle preserved as it preserves the data types
# # Read the CSVs

# # combined_df     (DataFrame)
# csv_path = "../sourcing_artifacts/pro_fb_ref_output_combined_01.csv"
# combined_df_restore = pd.read_csv(csv_path)

# display(f'rows : {len(combined_df_restore)}; cols: {len(combined_df_restore.columns)}')
# display(combined_df_restore.head())


# # quarterback_fails  (list)
# list_path = "../sourcing_artifacts/pro_fb_ref_output_fails_01.csv"
# quarterback_fails_restore = []
# # use next(reader) to retrieve the single row as a list, which simplifies the code and keeps quarterback_fails_restore as a flat list of items. 
# #   Each item will correspond to an element from the original quarterback_fails list.
# with open(list_path, mode='r') as file:
#     reader = csv.reader(file)
#     quarterback_fails_restore = next(reader)  # Using next() to get the first row as a single list

# print(f'length: {len(quarterback_fails_restore)}')
# print(f'restored {quarterback_fails_restore}')

In [9]:
# Read the PKls
import pickle
# combined_df     (DataFrame)
pkl_path1 = "../sourcing_artifacts/pro_fb_ref_output_combined_01.pkl"
with open(pkl_path1, 'rb') as f:
    combined_df_restore2 = pickle.load(f)

display(f'rows : {len(combined_df_restore2)}; cols: {len(combined_df_restore2.columns)}')
display(combined_df_restore2.head())


# quarterback_fails  (list)
pkl_path2 = "../sourcing_artifacts/pro_fb_ref_output_fails_01.pkl"
with open(pkl_path2, 'rb') as f:
    quarterback_fails_restore2 = pickle.load(f)

display(f'length: {len(quarterback_fails_restore2)}')
display(f'restored {quarterback_fails_restore2}')

'rows : 656; cols: 58'

,name,throws,hall_of_fame,college,high_school,weighted_career_av,overall_rank,college_stats,draft_team,draft_round,...,pass_rating,pass_sacked,pass_sacked_yds,pass_sacked_pct,pass_net_yds_per_att,pass_adj_net_yds_per_att,comebacks,gwd,av,nickname
0,Greg Cook,Right,,Cincinnati,Chillicothe,10,8386,https://www.sports-reference.com/cfb/players/g...,Cincinnati Bengals,1,...,87.6,29,195,12.66,7.29,6.44,1,0,10,NaN
1,Marty Domres,Right,8842,Columbia,Christian Brothers Academy,19,5811,https://www.sports-reference.com/cfb/players/m...,San Diego Chargers,1,...,53.8,79,588,8.90,4.86,2.93,3,2,21,NaN
2,Terry Hanratty,Right,8842,Notre Dame,Butler,8,9197,https://www.sports-reference.com/cfb/players/t...,Pittsburgh Steelers,2,...,43.0,34,299,7.31,4.75,2.40,3,2,8,NaN
3,Bobby Douglass,Left,8842,Kansas,El Dorado,37,2916,https://www.sports-reference.com/cfb/players/b...,Chicago Bears,2,...,48.5,180,1335,13.25,3.80,2.21,3,4,41,NaN
4,Al Woodall,Right,,Duke,Erwin,13,7362,https://www.sports-reference.com/cfb/players/a...,New York Jets,2,...,60.3,60,455,10.66,4.47,3.27,1,1,13,NaN

'length: 806'

'restored [\'Onree Jackson\', \'Onree Jackson\', \'Larry Good\', \'Larry Good\', \'Sonny Wade\', \'Sonny Wade\', \'Alan Pastrana\', \'Alan Pastrana\', \'Tim Carr\', \'Tim Carr\', \'Bob Belden\', \'Bob Belden\', \'Tom Boutwell\', \'Tom Boutwell\', \'Ed Roseborough\', \'Ed Roseborough\', \'Ed Hargett\', \'Ed Hargett\', "Buster O\'Brien", "Buster O\'Brien", \'Ronnie South\', \'Ronnie South\', \'John Schneider\', \'John Schneider\', \'Danny Holman\', \'Danny Holman\', \'Greg Barton\', \'Greg Barton\', \'Kim King\', \'Kim King\', \'Jim Alcorn\', \'Jim Alcorn\', \'Henry Johnson\', \'Henry Johnson\', \'Jim Haynie\', \'Jim Haynie\', \'Jeff Beaver\', \'Jeff Beaver\', \'Jimmy Raye\', \'Jimmy Raye\', \'Bob Lee\', \'Bob Lee\', \'Bob David\', \'Bob David\', \'Vidal Carlin\', \'Vidal Carlin\', \'Terry Southall\', \'Terry Southall\', \'Rick Egloff\', \'Rick Egloff\', \'Corey Colehour\', \'Corey Colehour\', \'Bruce Matte\', \'Bruce Matte\', \'John Foruria\', \'John Foruria\', \'Steve Laub\', \'Steve Laub\', \'Dave Bennett\', \'Dave Bennett\', \'Ben Monroe\', \'Ben Monroe\', \'Jack Lentz\', \'Jack Lentz\', \'Paul Brothers\', \'Paul Brothers\', \'Bill Buckner\', \'Bill Buckner\', \'Bob Biletnikoff\', \'Bob Biletnikoff\', \'Dan Talbott\', \'Dan Talbott\', \'Gary Snook\', \'Gary Snook\', \'Jack White\', \'Mike Brundage\', \'Mike Brundage\', \'Ken Lucas\', \'Ken Lucas\', \'Dave Neilson\', \'Dave Neilson\', \'Bob Timberlake\', \'Bob Timberlake\', \'Tommy Myers\', \'Tommy Myers\', \'Brig Owens\', \'Brig Owens\', \'Jhn Hankinson\', \'Jhn Hankinson\', \'Pat Screen\', \'Pat Screen\', \'Dan Simrell\', \'Dan Simrell\', \'Tom LaFramboise\', \'Tom LaFramboise\', \'Billy Guy Anderson\', \'Billy Guy Anderson\', \'John Torok\', \'John Torok\', \'Craig Fertig\', \'Craig Fertig\', \'George Haffner\', \'George Haffner\', \'Perry Lee Dunn\', \'Perry Lee Dunn\', \'Billy Lothridge\', \'Billy Lothridge\', \'Henry Schichtle\', \'Henry Schichtle\', \'Jack Ankerson\', \'Jack Ankerson\', \'Dave Mathieson\', \'Dave Mathieson\', \'Jim Turner\', \'Jim Turner\', \'John Furman\', \'John Furman\', \'Jim Bakken\', \'Jim Bakken\', \'Wilburn Hollis\', \'Wilburn Hollis\', \'Walt Rappold\', \'Walt Rappold\', \'Gale Weidner\', \'Gale Weidner\', \'Charlie Furlow\', \'Charlie Furlow\', \'Mel Rideout\', \'Mel Rideout\', \'Joe Zuger\', \'Joe Zuger\', \'Bob Joiner\', \'Bob Joiner\', \'John Anabo\', \'John Anabo\', \'Ed Trancygier\', \'Ed Trancygier\', \'Jim Wright\', \'Jim Wright\', \'Dick Thornton\', \'Dick Thornton\', \'Jake Gibbs\', \'Jake Gibbs\', \'Lowndes Shingler\', \'Lowndes Shingler\', \'Howard Dyer\', \'Howard Dyer\', \'Jack Moynihan\', \'Jack Moynihan\', \'Don Jonas\', \'Don Jonas\', \'Ben Charles\', \'Ben Charles\', \'George Izo\', \'George Izo\', \'Charley Britt\', \'Charley Britt\', \'Jack Cummings\', \'Jack Cummings\', \'Dick Norman\', \'Dick Norman\', \'Jacky Lee\', \'Jacky Lee\', \'Bobby Waters\', \'Bobby Waters\', \'Dave Grosz\', \'Dave Grosz\', \'Jim Waldon\', \'Jim Waldon\', \'Don Allard\', \'Don Allard\', \'Jim Grazione\', \'Jim Grazione\', \'Mitch Ogiego\', \'Mitch Ogiego\', \'Bob Ptacek\', \'Bob Ptacek\', \'Frank Kremblas\', \'Frank Kremblas\', \'Dan Nolan\', \'Dan Nolan\', \'Jim Van Pelt\', \'Jim Van Pelt\', \'Al Jacks\', \'Al Jacks\', \'Mickey Trimarki\', \'Mickey Trimarki\', \'Ken (Model-T) Ford\', \'Ken (Model-T) Ford\', \'Tom Forestal\', \'Tom Forestal\', \'Ronnie Knox\', \'Ronnie Knox\', \'Bobby Cox\', \'Bobby Cox\', \'Jimmy Harris\', \'Jimmy Harris\', \'Chuck Curtis\', \'Chuck Curtis\', \'Wade Mitchell\', \'Wade Mitchell\', \'Corny Salvaterra\', \'Corny Salvaterra\', \'Kenny Ploen\', \'Kenny Ploen\', \'Gene Cichowski\', \'Gene Cichowski\', \'Ronnie Quillian\', \'Ronnie Quillian\', \'Bob Winters\', \'Bob Winters\', \'Gary Glick\', \'Gary Glick\', \'Em Lindbeck\', \'Em Lindbeck\', \'John Polzer\', \'John Polzer\', \'Tom Spiers\', \'Tom Spiers\', \'George Welsh\', \'George Welsh\', \'Eagle Day\', \'Eagle Day\', \'Eddie West\', \'Eddie West\', \'Pete Neft\', \'Pete Neft\', \'Bobby Fox\', \'Bobby Fox\', \'Jerry Gustafson\', \'Jerry Gustafson\', \'John Shearer\', \'John Shearer\', \'Bobby Lance\', \'Bobby Lance\', \'Rod Hermes\', \'Rod Hermes\', \'Johnny Borton\', \'Johnny Borton\', \'Charley Brackins\', \'Charley Brackins\', \'Pete Vann\', \'Pete Vann\', \'Bobby Garrett\', \'Bobby Garrett\', \'Ted Marchibroda\', \'Ted Marchibroda\', \'Eddie Crowder\', \'Eddie Crowder\', \'Dale Samuels\', \'Dale Samuels\', \'Charlie Maloy\', \'Charlie Maloy\', \'Bill Brehany\', \'Bill Brehany\', \'Vito (Babe) Parilli\', \'Vito (Babe) Parilli\', \'Harry Agganis\', \'Harry Agganis\', \'Don Klosterman\', \'Don Klosterman\', \'Gary Kerkorian\', \'Gary Kerkorian\', \'Bob Williams\', \'Bob Williams\', \'Y.A. Tittle\', \'Y.A. Tittle\', \'John (Model-T) Ford\', \'John (Model-T) Ford\', \'Arnold Galiffa\', \'Arnold Galiffa\', \'Johnny Rauch\', \'Johnny Rauch\', \'Stan Heath\', \'Stan Heath\', \'Y.A. Tittle\', \'Y.A. Tittle\', \'Paul Campbell\', \'Paul Campbell\', \'Gil Johnson\', \'Gil Johnson\', \'Stan Heath\', \'Stan Heath\', \'Frank (Boley) Dancewicz\', \'Frank (Boley) Dancewicz\', \'Frank Broyles\', \'Frank Broyles\', \'Al Kowalski\', \'Al Kowalski\', \'Angelo Bertelli\', \'Angelo Bertelli\', \'Les Horvath\', \'Les Horvath\', \'Paul Christman\', \'Paul Christman\', \'Jack Odle\', \'Jack Odle\', "Davey O\'Brien", "Davey O\'Brien", \'Earl Crowder\', \'Earl Crowder\', \'Clarence (Ace) Parker\', \'Clarence (Ace) Parker\', \'Dan Manucci\', \'Dan Manucci\', \'Rick Leach\', \'Rick Leach\', \'Dave Marler\', \'Dave Marler\', \'Danny Sanders\', \'Danny Sanders\', \'Dave Rader\', \'Dave Rader\', \'Larry Fortner\', \'Larry Fortner\', \'Pete Woods\', \'Pete Woods\', \'Mark Manges\', \'Mark Manges\', \'Rob Hertel\', \'Rob Hertel\', \'Mike Rieker\', \'Mike Rieker\', \'Dennis Sproul\', \'Dennis Sproul\', \'Keith Myers\', \'Keith Myers\', \'John Hurley\', \'John Hurley\', \'Fred Besana\', \'Fred Besana\', \'Tommy Duniven\', \'Tommy Duniven\', \'Steve Mathieson\', \'Steve Mathieson\', \'Mark Vitali\', \'Mark Vitali\', \'Steve DeBerg\', \'Steve DeBerg\', \'Mike Cordova\', \'Mike Cordova\', \'Gene Swick\', \'Gene Swick\', \'Bob Bateman\', \'Bob Bateman\', \'Scott Gardner\', \'Scott Gardner\', \'Craig Nagel\', \'Craig Nagel\', \'Steve Kincannon\', \'Steve Kincannon\', \'Bill Salmon\', \'Bill Salmon\', \'Greg Kokal\', \'Greg Kokal\', \'Cornelius Greene\', \'Cornelius Greene\', \'Dave Buckey\', \'Dave Buckey\', \'Joe Bruner\', \'Joe Bruner\', \'Steve Hamilton\', \'Steve Hamilton\', \'Mark Driscoll\', \'Mark Driscoll\', \'Lynn Hieber\', \'Lynn Hieber\', \'Jack Berry\', \'Jack Berry\', \'Jeff Grantz\', \'Jeff Grantz\', \'Gary Sheide\', \'Gary Sheide\', \'Tom Shuman\', \'Tom Shuman\', \'Steve Joachim\', \'Steve Joachim\', \'Harry Knight\', \'Harry Knight\', \'Rich Worley\', \'Rich Worley\', \'Jim McMillan\', \'Jim McMillan\', \'John Graham\', \'John Graham\', \'Tom Doyle\', \'Tom Doyle\', \'Chris Kupec\', \'Chris Kupec\', \'Alvin White\', \'Alvin White\', \'Bill Malouf\', \'Bill Malouf\', \'Mitch Anderson\', \'Mitch Anderson\', \'Alan Chadwick\', \'Alan Chadwick\', \'Greg Hare\', \'Greg Hare\', \'Gary Valbuena\', \'Gary Valbuena\', \'Bob Bobrowski\', \'Bob Bobrowski\', \'Keith Bobo\', \'Keith Bobo\', \'Frank Kolch\', \'Frank Kolch\', \'Don Van Galder\', \'Don Van Galder\', \'Larry Gipa\', \'Larry Gipa\', \'Peil Pennington\', \'Peil Pennington\', \'Craig Holland\', \'Craig Holland\', \'Mike Wells\', \'Mike Wells\', \'Randolph Mattingly\', \'Randolph Mattingly\', \'Dan Werner\', \'Dan Werner\', \'Mike Rae\', \'Mike Rae\', \'Ty Paine\', \'Ty Paine\', \'Matthew Reed\', \'Matthew Reed\', \'Tom Pierantozzi\', \'Tom Pierantozzi\', \'John Madeys\', \'John Madeys\', \'Ted McNulty\', \'Ted McNulty\', \'Eddie McAshan\', \'Eddie McAshan\', \'Eric Crone\', \'Eric Crone\', \'Wayne Estabrook\', \'Wayne Estabrook\', \'Jim Fassel\', \'Jim Fassel\', \'Van Brownson\', \'Van Brownson\', \'Craig Curry\', \'Craig Curry\', \'Mike Franks\', \'Mike Franks\', \'Don Bunce\', \'Don Bunce\', \'James Hamilton\', \'James Hamilton\', \'Eric Guthrie\', \'Eric Guthrie\', \'Rusty Lachaussee\', \'Rusty Lachaussee\', \'Brian Linstrom\', \'Brian Linstrom\', \'Gary Wichard\', \'Gary Wichard\', \'Gordon Longmire\', \'Gordon Longmire\', \'Kelly Cochrane\', \'Kelly Cochrane\', \'Karl Douglas\', \'Karl Douglas\', \'Bryant Salter\', \'Bryant Salter\', \'Frank Harris\', \'Frank Harris\', \'Buddy Lee\', \'Buddy Lee\', \'Rex Kern\', \'Rex Kern\', \'Charlie Richards\', \'Charlie Richards\', \'Tim Von Dulm\', \'Tim Von Dulm\', \'Steve Goepel\', \'Steve Goepel\', \'Busty Underwood\', \'Busty Underwood\', \'Craig Blackford\', \'Craig Blackford\', \'Chuck Hixon\', \'Chuck Hixon\', \'Bill Bynum\', \'Bill Bynum\', \'Ron Maciejowski\', \'Ron Maciejowski\', \'Bob Cutburth\', \'Bob Cutburth\', \'Rusty Clark\', \'Rusty Clark\', \'Mike Cilek\', \'Mike Cilek\', \'Gordon Slade\', \'Gordon Slade\', \'Mike Holmgren\', \'Mike Holmgren\', \'Larry Arnold\', \'Larry Arnold\', \'Bob Stewart\', \'Bob Stewart\', \'Billy Joe Tolliver\', \'Billy Joe Tolliver\', \'Jeff Francis\', \'Jeff Francis\', \'Brent Snyder\', \'Brent Snyder\', \'Terrance Jones\', \'Terrance Jones\', \'Paul Singer\', \'Paul Singer\', \'Bob Jean\', \'Bob Jean\', \'Wayne Johnson\', \'Wayne Johnson\', \'Steve Taylor\', \'Steve Taylor\', \'Chuck Hartlieb\', \'Chuck Hartlieb\', \'Tom Tupa\', \'Tom Tupa\', \'Don McPherson\', \'Don McPherson\', \'Mike Perez\', \'Mike Perez\', \'Bud Keyes\', \'Bud Keyes\', \'Todd Santos\', \'Todd Santos\', \'Danny McCoin\', \'Danny McCoin\', \'Danny McManus\', \'Danny McManus\', \'David Weber\', \'David Weber\', \'Steve Slayden\', \'Steve Slayden\', \'Doug Hudson\', \'Doug Hudson\', \'Sammy Garza\', \'Sammy Garza\', \'Ken Lambiotte\', \'Ken Lambiotte\', \'John Paye\', \'John Paye\', \'Dave Walter\', \'Dave Walter\', \'Mike Shula\', \'Mike Shula\', \'Jim Karsatos\', \'Jim Karsatos\', \'Bill Ransdell\', \'Bill Ransdell\', \'Robbie Bosco\', \'Robbie Bosco\', \'Doug Gaynor\', \'Doug Gaynor\', \'Mike Norseth\', \'Mike Norseth\', \'Jeff Wickersham\', \'Jeff Wickersham\', \'Chris Hegg\', \'Chris Hegg\', \'David Norrie\', \'David Norrie\', \'Kent Austin\', \'Kent Austin\', \'Brian McClure\', \'Brian McClure\', \'Steve Bradley\', \'Steve Bradley\', \'Scott Barry\', \'Scott Barry\', \'Steve Calabria\', \'Steve Calabria\', \'Paul Berner\', \'Paul Berner\', \'Buddy Funck\', \'Buddy Funck\', \'Joe Shield\', \'Joe Shield\', \'Rick McIvor\', \'Rick McIvor\', \'Dean May\', \'Dean May\', \'Ben Bennett\', \'Ben Bennett\', \'Terry Nugent\', \'Terry Nugent\', \'Mark Casale\', \'Mark Casale\', \'Randy Essington\', \'Randy Essington\', \'Jeff Christensen\', \'Jeff Christensen\', \'Reggie Collier\', \'Reggie Collier\', \'Jim Bob Taylor\', \'Jim Bob Taylor\', \'Clete Castper\', \'Clete Castper\', \'David Mangrum\', \'David Mangrum\', \'Scott Lindquist\', \'Scott Lindquist\', \'Mike Kelley\', \'Mike Kelley\', \'Luc Tousignant\', \'Luc Tousignant\', \'Bob Lane\', \'Bob Lane\', \'Bryan Clark\', \'Bryan Clark\', \'Ron Reeves\', \'Ron Reeves\', \'Steve Michuta\', \'Steve Michuta\', \'Steve Sandon\', \'Steve Sandon\', \'Dan Feraday\', \'Dan Feraday\', \'Brad Wright\', \'Brad Wright\', \'Mark Reed\', \'Mark Reed\', \'Nickie Hall\', \'Nickie Hall\', \'Phil Kessel\', \'Phil Kessel\', \'Tim Clifford\', \'Tim Clifford\', \'Rick Trocano\', \'Rick Trocano\', \'Brian Buckley\', \'Brian Buckley\', "Mark O\'Connell", "Mark O\'Connell", \'Gene Bradley\', \'Gene Bradley\', \'Craig Bradshaw\', \'Craig Bradshaw\', \'Todd Krueger\', \'Todd Krueger\', \'Dan Hartwig\', \'Dan Hartwig\', \'Mike Wright\', \'Mike Wright\', \'Jimmy Jordan\', \'Jimmy Jordan\', \'Kevin Scanlon\', \'Kevin Scanlon\', \'Kevin Daft\', \'Kevin Daft\', \'Pat Barnes\', \'Pat Barnes\', \'Chuck Clements\', \'Chuck Clements\', \'Tony Corbin\', \'Tony Corbin\', \'Ronnie McAda\', \'Ronnie McAda\', \'Spence Fischer\', \'Spence Fischer\', \'Mike Cawley\', \'Mike Cawley\', \'Jon Stark\', \'Jon Stark\', \'Kyle Wachholtz\', \'Kyle Wachholtz\', \'Chad May\', \'Chad May\', \'Dave Barr\', \'Dave Barr\', \'Jay Barker\', \'Jay Barker\', \'Jerry Colquitt\', \'Jerry Colquitt\', \'John Walsh\', \'John Walsh\', \'Perry Klein\', \'Perry Klein\', \'Jay Walker\', \'Jay Walker\', \'Billy Joe Hobert\', \'Billy Joe Hobert\', \'Gino Torretta\', \'Gino Torretta\', \'Chris Hakel\', \'Chris Hakel\', \'Mike Pawlawski\', \'Mike Pawlawski\', \'Mark Barsotti\', \'Mark Barsotti\', \'Keithen McCant\', \'Keithen McCant\', \'Cornelius Benton\', \'Cornelius Benton\', \'Matt Rodgers\', \'Matt Rodgers\', \'Bill Muscrave\', \'Bill Muscrave\', "Pat O\'Hara", "Pat O\'Hara", \'Jeff Bridewell\', \'Jeff Bridewell\', \'Larry Wanke\', \'Larry Wanke\', \'Tommy Hodson\', \'Tommy Hodson\', \'Peter Tom Willis\', \'Peter Tom Willis\', \'Craig Kupp\', \'Craig Kupp\', \'Gerry Gdowski\', \'Gerry Gdowski\', \'Kirk Baumgartner\', \'Kirk Baumgartner\', \'Todd Ellis\', \'Todd Ellis\', \'Clemente Gordon\', \'Clemente Gordon\', \'Todd Hammel\', \'Todd Hammel\', \'Gene Benhart\', \'Gene Benhart\', \'John Gromos\', \'John Gromos\', \'Major Harris\', \'Reggie Slack\', \'Reggie Slack\', \'John David Booty\', \'John David Booty\', \'Josh Johnson\', "Andre\' Woodson", "Andre\' Woodson", \'Jordan Palmer\', \'Jordan Palmer\', \'Omar Jacobs\', \'Omar Jacobs\', \'D.J. Shockley\', \'D.J. Shockley\', \'David Greene\', \'David Greene\', \'Stefan Lefors\', \'Stefan Lefors\', \'Adrian McPherson\', \'Adrian McPherson\', \'James Kilian\', \'James Kilian\', \'J.P. Losman\', \'J.P. Losman\', \'Jeff Smoker\', \'Jeff Smoker\', \'Casey Bramlet\', \'Casey Bramlet\', \'B.J. Symons\', \'B.J. Symons\', \'Brian St. Pierre\', \'Brian St. Pierre\', \'Brandon Doman\', \'Brandon Doman\', "J.T. O\'Sullivan", "J.T. O\'Sullivan", \'Steve Bellisari\', \'Steve Bellisari\', \'Seth Burford\', \'Seth Burford\', \'Jeff Kelly\', \'Jeff Kelly\', \'Wes Pate\', \'Wes Pate\', \'A.J. Feeley\', \'A.J. Feeley\', \'Josh Booty\', \'Josh Booty\', \'Josh Heupel\', \'Josh Heupel\', \'Giovanni Carmazzi\', \'Giovanni Carmazzi\', \'Todd Husak\', \'Todd Husak\', \'JaJuan Seider\', \'JaJuan Seider\', \'Joe Hamilton\', \'Joe Hamilton\', \'Daniel Jones\', \'Tanner Lee\', \'Tanner Lee\', \'C.J. Beathard\', \'C.J. Beathard\', \'A.J. McCarron\', \'A.J. McCarron\', \'B.J. Daniels\', \'B.J. Daniels\', \'B.J. Coleman\', \'B.J. Coleman\', \'T.J. Yates\', \'T.J. Yates\', \'Bo Nix\', \'Bo Nix\', \'Malik Willis\', \'Mac Jones\', \'Jordan Love\', \'Jordan Love\']'

In [10]:
df = combined_df_restore2.copy()
quarterback_fails = quarterback_fails_restore2

display(df.iloc[:,:15].tail(5))
display(df.iloc[:,15:30].tail(5))
display(df.iloc[:,30:45].tail(5))
display(df.iloc[:,45:].tail(5))
display(len(quarterback_fails))

,name,throws,hall_of_fame,college,high_school,weighted_career_av,overall_rank,college_stats,draft_team,draft_round,draft_pick,draft_year,games_played,approximate_value,qb_record
651,Jake Luton,Right,,Idaho,,2,13593,https://www.sports-reference.com/cfb/players/j...,Jacksonville Jaguars,6,189,2020,3,2,0-3-0
652,Cole McDonald,,,Hawaii,,,,https://www.sports-reference.com/cfb/players/c...,Tennessee Titans,7,224,2020,N/A,N/A,N/A
653,Ben DiNucci,Right,,Pittsburgh,Pine-Richland,1,15158,https://www.sports-reference.com/cfb/players/b...,Dallas Cowboys,7,231,2020,3,1,0-1-0
654,Tommy Stevens,Right,,Penn St.,,0,17659,https://www.sports-reference.com/cfb/players/t...,New Orleans Saints,7,240,2020,1,N/A,N/A
655,Nate Stanley,,,Iowa,,,,https://www.sports-reference.com/cfb/players/n...,Minnesota Vikings,7,244,2020,N/A,N/A,N/A

,completion_percentage,passing_yards,yards_per_attempt,touchdowns,interceptions,fantasy_points,all_star,uniforms,when_born,where_born,height,weight,pass_yards,TD,superbowls
651,54.5,624,5.7,2,6,28.3,N/A,N/A,"April 11, 1996","Marysville, WA",6-6,224,624,2,NaN
652,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,"May 20, 1998",NaN,6-3,215,NaN,NaN,NaN
653,53.5,219,5.1,0,0,7.0,N/A,N/A,"November 24, 1996","Atlanta, GA",6-2,215,219,NaN,NaN
654,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,"December 15, 1996","Indianapolis, IN",6-5,235,NaN,NaN,NaN
655,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,"August 26, 1997",NaN,6-4,235,NaN,NaN,NaN

,retire_year,years,games,games_started,qb_rec,pass_cmp,pass_att,pass_cmp_pct,pass_yds,pass_td,pass_td_pct,pass_int,pass_int_pct,pass_long,pass_yds_per_att
651,2020,1 Yr,3,3,0-3-0,60,110,54.5,624,2,1.8,6,5.5,31,41.0
652,NaN,,,,,,,,,,,,,,
653,NaN,1 Yr,3,1,0-1-0,23,43,53.5,219,0,0.0,0,0.0,11,34.0
654,2020,1 Yr,1,0,4,24,0,2,100.0,10,6.0,24.0,4.0,0,0
655,NaN,,,,,,,,,,,,,,

,pass_adj_yds_per_att,pass_yds_per_cmp,pass_yds_per_g,pass_rating,pass_sacked,pass_sacked_yds,pass_sacked_pct,pass_net_yds_per_att,pass_adj_net_yds_per_att,comebacks,gwd,av,nickname
651,73,5.7,3.58,10.4,208.0,54.5,,7,52,5.98,4.89,2.92,NaN
652,,,,,,,,,,,,,NaN
653,32,5.1,5.09,9.5,73.0,67.9,,7,73,14.00,2.92,2.92,NaN
654,0,0,0,0.0,0.0,4,6.0,24,0,0,0,,NaN
655,,,,,,,,,,,,,NaN

806

### Bring in nfl_career_statistics.csv  to get QB names, etc.

In [162]:
# get lists of QBs to get data for:
rel_path = "../Data_Artifacts/nfl_career_statistics.csv"
qb_name_df = pd.read_csv(rel_path)
print(len(qb_name_df))

qb_name_df.head()

# import os
# absolute_path = os.path.abspath(rel_path)
# print(f"Absolute path: {absolute_path}")

# # Check if the file exists and open it with the default application
# if os.path.exists(absolute_path):
#     os.startfile(absolute_path)
#     print('Opened with default application.')
# else:
#     print(f'File not found at: {absolute_path}')

637

,player,drafted,yrs_played,teams,hof,wAV,earnings_mils,comp_%,pass_rating,comp,att,pass_yds,TD,pass_yds_game,int,int_%,pick_6,sacks,4QC,GWD
0,Tom Brady,2000.0,23.0,"['Patriots', 'Buccaneers']",0.0,184.0,317.620,64.3,97.2,7753.0,12050.0,89214.0,649.0,266.0,212.0,1.8,18.0,565.0,46.0,58.0
1,Drew Brees,2001.0,20.0,"['Saints', 'Chargers']",0.0,167.0,273.933,67.7,98.7,7142.0,10551.0,80358.0,571.0,280.0,243.0,2.3,27.0,420.0,36.0,53.0
2,Peyton Manning,1998.0,18.0,"['Colts', 'Broncos']",1.0,176.0,247.714,65.3,96.5,6125.0,9380.0,71940.0,539.0,270.0,251.0,2.7,27.0,303.0,43.0,54.0
3,Brett Favre,1991.0,20.0,"['Packers', 'Vikings', 'Jets', 'Falcons']",1.0,158.0,141.407,62.0,86.0,6300.0,10169.0,71838.0,508.0,237.0,336.0,3.3,32.0,525.0,28.0,43.0
4,Ben Roethlisberger,2004.0,18.0,['Steelers'],0.0,131.0,266.724,64.4,93.5,5440.0,8443.0,64088.0,418.0,257.0,211.0,2.5,18.0,554.0,41.0,53.0

### ** ALL REMAINING CELLS: NOT USED **